### ISSUE TITLE
Null pointer error caused by non-validator

### ISSUE THREAD

**Issue by alphaqiu** [mosaicnetworks/babble#122]
The situation is this, I have established 3 nodes for the monet hub, and the fourth node applied to join the monet hub. The fourth node in the middle exits, and an error is reported when exiting.

https://github.com/mosaicnetworks/babble/blob/4861183f290ce1325f576feec92d8e78591398e0/src/node/core.go#L417

```go
func (c *Core) Leave(leaveTimeout time.Duration) error {
	// Do nothing if we are not a validator.
	p, ok := c.validators.ByID[c.validator.ID()]
	if !ok {
		c.logger.Debugf("Leave: not a validator, do nothing")
	}

	// Do nothing if we are the only validator.
	if len(c.validators.Peers) <= 1 {
		c.logger.Debugf("Leave: alone, do nothing")
		return nil
	}

	// Otherwise, submit an InternalTransaction

	c.logger.Debugf("Leave: submit InternalTransaction")

	itx := hg.NewInternalTransaction(hg.PEER_REMOVE, *p)
```

due to
```go
p, ok := c.validators.ByID[c.validator.ID()]
If !ok {
c.logger.Debugf("Leave: not a validator, do nothing")
}
```
It is judged that it is a non-validator node, so `p` is nil. The following call to `itx := hg.NewInternalTransaction(hg.PEER_REMOVE, *p)` causes a null pointer error.

**Comment by alphaqiu** [comment]
here is a logs.
```go
DEBU[0010] JOINING                                       this_id=3849552763
^CDEBU[0017] Reacting to SIGINT - LEAVE                    this_id=3849552763
DEBU[0017] LEAVING                                       this_id=3849552763
DEBU[0017] Leave: not a validator, do nothing            id=3849552763
DEBU[0017] Leave: submit InternalTransaction             id=3849552763
DEBU[0017] Shutdown                                      this_id=3849552763
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4584949]

goroutine 10453 [running]:
github.com/mosaicnetworks/babble/src/node.(*Core).Leave(0xc0022a80d0, 0x2540be400, 0xc000166000, 0x1)
	${Gopath}/src/github.com/mosaicnetworks/babble/src/node/core.go:417 +0xf9
github.com/mosaicnetworks/babble/src/node.(*Node).Leave(0xc000166000, 0x0, 0x0)
	${Gopath}/src/github.com/mosaicnetworks/babble/src/node/node.go:169 +0xda
github.com/mosaicnetworks/babble/src/node.(*Node).doBackgroundWork(0xc000166000)
	${Gopath}/src/github.com/mosaicnetworks/babble/src/node/node.go:290 +0x1ae
created by github.com/mosaicnetworks/babble/src/node.(*Node).Run
	${Gopath}/src/github.com/mosaicnetworks/babble/src/node/node.go:134 +0x8c
```

This will cause the entire network to hang and cannot be used for consensus.
```
DEBU[0016] Sync                                          id=2271564749 unknown_events=1000
ERRO[0016] Reading WireEvent                             error="Participant 3849552763 not found" id=2271564749 wire_event="{{[] [] [] 167545333 3849552763 168 167 2} 26pusqllh9ao6n5a5mdjos6pagb1nzrp3ihvbnjrf99j3nbhyz|668sb9s8ux866uesy5rs1rysfrx3jg7i3ggfq5wphqkqfz37pm}"
DEBU[0016] Sync()                                        duration=44352 this_id=2271564749
ERRO[0016]                                               error="Participant 3849552763 not found" this_id=2271564749
ERRO[0016] sync()                                        error="Participant 3849552763 not found" this_id=2271564749
```

**Comment by arrivets** [comment]
Thanks for the detailed logs.
I added a "return nil " when it's not a validator. 
The change was made on the develop branch, which we are going to merge tomorrow along with a lot of fixes for monetd and evm-lite.
